#!/bin/sh
#
# $Id: xpsvn 12515 2010-08-18 13:18:56Z friebe $
#

MYSELF=$(realpath "$0")
DIRNAME=$(dirname "$MYSELF")

# Display usage if no args have been given
if [ $# -eq 0 ]; then
  cat "$DIRNAME/xpsvn.usage"
  exit 1;
fi

# Include commonly used functions:
. "$DIRNAME"/xpsvn-cmd/common.inc.sh

exitHandler() {
  exit $?
}

COMMAND=$1
shift 1 2>/dev/null;

[ $DEBUG ] && echo "---> Command= $COMMAND $*"

trap exitHandler EXIT

# Handle command "symlinks"
case $COMMAND in
  tst)
    COMMAND="tagstatus"
    ;;
  tdi)
    COMMAND="tagdiff"
    ;;
  tci)
    COMMAND="tagcommit"
    ;;
  tup)
    COMMAND="tagupdate"
    ;;
  tn)
    COMMAND="tagname"
    ;;
esac

if [ -f "$DIRNAME"/xpsvn-cmd/cmd.${COMMAND}.sh ]; then
  . "$DIRNAME"/xpsvn-cmd/cmd.${COMMAND}.sh "$@"
  exit $RETCODE
fi

# Display usage
cat "$DIRNAME/xpsvn.usage"
exit 1;
