<?php
/*
 * This file is part of the ${artifactId} library
 *
 */

/**
 * This class was generated by xpframework-archetype-library
 *
 * @test xp://unittest.${package}.${artifactId}.Greeting
 */
class Greeting extends Object {

  /**
   * Get greeting for the provided name
   *
   * @param  string $name
   * @return string
   */
  public static function getGreeting($name) {

    // Sanity check
    if (NULL === $name || '' === $name) {
      throw new IllegalArgumentException('The provided name is invalid');
    }

    // Return greeting
    return 'Hello '.$name.'!';
  }
}
?>
